### ISSUE TITLE
A question on pyqt5

### ISSUE THREAD

**Issue by ns696** [pyqt/examples#13]
I am making a software and gonna distribute it (for free),so still I need to buy a licence from riverbank?

**Comment by mherrmann** [comment]
I'm not a lawyer but here's my understanding.

PyQt5 is licensed under the GPL. This essentially means that you can use it for free provided that you make your source code accessible to anyone who also gets a binary copy of your app. The license under which you are required to make your source code accessible is again the GPL.

So: If you distribute your software for free online, then you need to release your source code under the GPL. In practice, this wold mean that you'd upload your source code to GitHub and create a `LICENSE` file that contains the contents of the GPL. I think you also need to include a copy of the GPL in your application. (Say in an `About...` dialog.)

Hope this helps.

**Comment by ns696** [comment]
But If don't wanna release then too I wanna need licence ??,or I need to move to pyside2

**Comment by mherrmann** [comment]
You only need to buy a license if you are want to give your software to people without giving them the source code. So if you "don't want to release", then you don't need a license.
