### ISSUE TITLE
Another example of PyQt usage?

### ISSUE THREAD

**Issue by ghost** [pyqt/examples#2]
I made a video course for Packt on Reactive programming with Python and it included a bunch of code for using PyQt5 as well:

* [simple hello world](https://github.com/rudolfolah/Reactive-Programming-in-Python/blob/master/Section%201/pyqt-test.py)
* desktop client for a simple stock exchange:
  * [using QTableWidget](https://github.com/rudolfolah/Reactive-Programming-in-Python/blob/master/Section%206/client/stock_overview_table.py)
  * [using QGridLayout](https://github.com/rudolfolah/Reactive-Programming-in-Python/blob/master/Section%206/client/client_window.py#L14-L19)
  * [using QFormLayout](https://github.com/rudolfolah/Reactive-Programming-in-Python/blob/master/Section%206/client/transaction_form.py#L22-L27)
  * [using the textChanged callback with QLineEdit](https://github.com/rudolfolah/Reactive-Programming-in-Python/blob/master/Section%206/client/transaction_form.py#L30-L33)

The example is a bit bigger than just showcasing one widget, it would be nice to include a link to https://github.com/rudolfolah/Reactive-Programming-in-Python/blob/master/Section%206/client/

**Alternatively**, I could create a PR that simplifies that example further but still gives devs an opportunity to see an example of using multiple PyQt widgets with multiple windows/forms/layouts.

**Comment by mherrmann** [comment]
I think we already have enough PyQt examples now. But thank you.
